# Autogenerated wrapper script for Help2man_jll for any
export help2man

JLLWrappers.@generate_wrapper_header("Help2man")
JLLWrappers.@declare_file_product(help2man)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_file_product(
        help2man,
        "bin/help2man",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
